version: '3'
services:
  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    environment:
      - CLUSTER_NAME=test
    ports:
      - "50070:50070"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
  spark:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8080:8080"
    volumes:
      - spark_master:/spark/dfs/name

volumes:
  hadoop_namenode:
  spark_master:
